---
- name: insatll lamp ans delete lemp 
  hosts: localhost
  become: yes
  vars:
    web_pkg: nginx
    web_pkg2: httpd
    db_pkg: mariadb105-server
    php_pkg:
      - php
      - php-fpm
    web_service: httpd
    db_service: mariadb
    php_service: php-fpm
    path: /use/share/nginx/html/index.php
    content: "<?php phpinfo(); ?>"
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: "{{web_pkg}}"
      state: present
  - name: stop httpd
    ansible.builtin.systemd_service:
      name: "{{web_pkg2}}"
      state: stopped
      enabled: false
  - name: install mariadb
    ansible.builtin.dnf: 
     name: "{{db_pkg}}"
     state: present
  - name: install php php-fpm
    ansible.builtin.dnf:
     name: "{{php_pkg}}"
     state: present
  - name: start httpd
    ansible.builtin.systemd_service:
     name: "{{web_service}}"
     state: started
     enabled: true
  - name : start name 
    ansible.builtin.systemd_service:
     name: "{{db_service}}"
     state: started
     enabled: true
  - name: start php-fpm
    ansible.builtin.systemd_service:    
      name: "{{php_service}}"
      state: started
      enabled: true
  - name: deployed 
    ansible.builtin.copy:
      dest: "{{path}}"
      content: "{{content}}"
